### PR TITLE
Bug fixes for two problems

### PR DESCRIPTION
**Pull request by magjac**
Fixes https://github.com/mstefaniuk/graph-viz-d3-js/issues/30 and https://github.com/mstefaniuk/graph-viz-d3-js/issues/35

### CODE REVIEW

**Comment by magjac** [comment]
I don't understand why this failed. Tests ran fine locally and this seem to be some kind of build environment problem. Is it possible to trigger a new test?

**Comment by magjac** [comment]
Log from local test:
```
> env DISPLAY=:1 npm test

> graphviz-d3-renderer@0.9.24 test /home/magjac/luser3/git/graph-viz-d3-js
> grunt test

Running "bower:unit" (bower) task
>> Installed bower packages
>> Copied packages to /home/magjac/luser3/git/graph-viz-d3-js/lib
>> Cleaned bower dir /home/magjac/luser3/git/graph-viz-d3-js/bower_components

Running "karma:unit" (karma) task
16 06 2017 23:29:07.528:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
16 06 2017 23:29:07.536:INFO [launcher]: Starting browser Firefox
16 06 2017 23:29:09.941:INFO [Firefox 48.0.0 (Ubuntu 0.0.0)]: Connected on socket Yugogc0pAPkiS_3hAAAA with id 37363878
Firefox 48.0.0 (Ubuntu 0.0.0): Executed 241 of 247 (skipped 6) SUCCESS (1.871 secs / 1.783 secs)

Done, without errors.
```

**Comment by magjac** [comment]
Close and reopen PR was the trick.

**Comment by mstefaniuk** [comment]
It seems that test timeout should be extended.

**Pull request merged**
